site_name: Ligato Docs
site_description: Ligato Documentation
site_url: https://docs.ligato.io/
repo_url: https://github.com/ligato/docs.ligato.io
site_author: "The Ligato Project"
copyright: "Copyright &copy; 2017-2019"

use_directory_urls: true

theme:
  name: readthedocs
  issue_tracker: https://github.com/ondrej-fabry/agent/issues

extra_css:
  - css/extra.css

nav:
  - INTRODUCTION:
    - Introduction: intro/index.md
    - CNF definition: intro/cnf-definition.md
    - Overview: intro/overview.md
    - CN-Infra: intro/cn-toc-file.md
    - KV datastore: intro/kv-store.md
  - USER GUIDE:
    - Quickstart guide: user-guide/quickstart.md
    - Learn how to: user-guide/learn-how-to.md
    - Concepts: user-guide/concepts.md
    - References: user-guide/references.md
    - Default VPP plugins: user-guide/default-vpp-plugins.md
    - Other VPP plugins: user-guide/other-vpp-plugins.md
    - Linux plugins: user-guide/linux-plugins.md
    - Framework plugins: user-guide/framework-plugins.md
  - DEVELOPER GUIDE:
    - KV Descriptors: developer-guide/implementing-your-own-kvdescriptor.md
    - Plugin lookup: developer-guide/plugin-lookup.md
    - Go Docs: developer-guide/godocs.md
  - TUTORIALS:
    - Hello World: tutorials/01_hello-world.md
    - Plugin Dependencies: tutorials/02_plugin-deps.md
    - REST Handler: tutorials/03_rest-handler.md
    - KV Datastore: tutorials/04_kv-store.md
    - KV Scheduler: tutorials/05_kv-scheduler.md
    - Plugin Lookup: tutorials/06_plugin-lookup.md
    - VPP Connection: tutorials/07_vpp-connection.md
  - TESTING:
    - CSIT tests locally: testing/tests-locally.md
    - Robot framework guide: testing/robot-framework-guide.md
  - TOOLS:
      - VPP-Agent-Ctl: tools/vpp-agent-ctl.md
  - TROUBLESHOOTING:
    - FAQ: troubleshooting/faq.md

markdown_extensions:
  - extra
  - admonition
  - smarty
  - codehilite
  - toc:
      permalink: true
